_target_: image2layout.train.models.generator.RetrievalAugmentedDSGenerator
_partial_: true

retrieval_backbone: dreamsim
random_retrieval: false
top_k: 16
saliency_k: None
use_reference_image: false
num_lstm_layers: 16