_target_: image2layout.train.models.generator.ConcateAuxilaryTaskConcateCrossAttnRetrievalAugmentedAutoreg
_partial_: true

retrieval_backbone: dreamsim
random_retrieval: false
top_k: 16
saliency_k: None
auxilary_task: uncond